name: Build wheels

# Build on every branch push, tag push, and pull request change:
on: [push, pull_request, workflow_dispatch]

# Alternatively, to publish when a (published) GitHub Release is created, use the following:
# on:
#   push:
#   pull_request:
#   release:
#     types:
#       - published

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]

    steps:
      - uses: actions/checkout@v3

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.13.1
        with:
          package-dir: Manylinux2014_Compliant_Source/pkg
        env:
          CIBW_SKIP: "pp*"
          CIBW_ARCHS: "x86_64"
          CIBW_MANYLINUX_X86_64_IMAGE: "ghcr.io/necessary129/manylinux2014-llvm:12-x86_64"
          CIBW_MUSLLINUX_X86_64_IMAGE: "ghcr.io/necessary129/musllinux-llvm:12-x86_64"
          CIBW_BEFORE_ALL: "bash Manylinux2014_Compliant_Source/pkg/build.sh"

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl